-- +goose Up
CREATE TABLE IF NOT EXISTS `articles` (`id` text,`account_id` text NOT NULL,`conversation_id` text NOT NULL,`reply_to_id` text,`reply_to_handle` text,`created_at` datetime NOT NULL,`full_text` text NOT NULL,`lang` text NOT NULL DEFAULT "ja",`full_text_ja` text,`full_text_en` text,`full_text_zh` text,`via` text NOT NULL,`is_repost` boolean NOT NULL DEFAULT false,`is_liked` boolean NOT NULL DEFAULT false,`wayback_url` text NOT NULL, `is_trash` boolean NOT NULL DEFAULT false, `trashed_by` text, `trash_reason` text, `trashed_at` datetime, `source_domain` text, `original_url` text, `sotwe_url` text, `nitter_url` text, `twistalker_url` text, source_name TEXT,PRIMARY KEY (`id`),CONSTRAINT `fk_accounts_articles` FOREIGN KEY (`account_id`) REFERENCES `accounts`(`numeric_id`));
CREATE INDEX IF NOT EXISTS `idx_articles_is_liked` ON `articles`(`is_liked`);
CREATE INDEX IF NOT EXISTS `idx_articles_created_at` ON `articles`(`created_at`);
CREATE INDEX IF NOT EXISTS `idx_articles_conversation_id` ON `articles`(`conversation_id`);
CREATE INDEX IF NOT EXISTS `idx_articles_account_id` ON `articles`(`account_id`);
CREATE TABLE IF NOT EXISTS `whitelists` (`id` integer PRIMARY KEY AUTOINCREMENT,`type` text NOT NULL,`value` text NOT NULL,`is_active` boolean NOT NULL DEFAULT true, `group_name` text DEFAULT "", `alias_of` text DEFAULT "");
CREATE UNIQUE INDEX IF NOT EXISTS `idx_whitelists_value` ON `whitelists`(`value`);
CREATE TABLE IF NOT EXISTS "url_redirects"  (`short_url` text,`expanded_url` text NOT NULL,`article_id` text NOT NULL,PRIMARY KEY (`short_url`),CONSTRAINT `fk_articles_url_redirects` FOREIGN KEY (`article_id`) REFERENCES `articles`(`id`));
CREATE INDEX IF NOT EXISTS `idx_url_redirects_article_id` ON `url_redirects`(`article_id`);
CREATE INDEX IF NOT EXISTS idx_articles_account_created ON articles (account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_whitelist_type_active ON whitelists (type, is_active);
CREATE INDEX IF NOT EXISTS idx_articles_is_liked_created ON articles(is_liked, created_at DESC) WHERE is_liked = 1;
CREATE INDEX IF NOT EXISTS idx_articles_conversation ON articles(conversation_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_articles_reply_to ON articles(reply_to_id);
CREATE TABLE IF NOT EXISTS "media"  (`media_id` text,`article_id` text NOT NULL,`type` text NOT NULL,`download_url` text NOT NULL,`width` integer NOT NULL,`height` integer NOT NULL,`download_status` text NOT NULL DEFAULT "QUEUED",`failed_reason` text,`stash_scene_id` text,`stash_image_id` text,`is_bookmarked` boolean DEFAULT false,`media_quality` text DEFAULT "", tweet_urls TEXT DEFAULT '[]', thumbnail_url TEXT, `is_trash` boolean NOT NULL DEFAULT false, `trashed_by` text, `trash_reason` text, `trashed_at` datetime, account_id TEXT,PRIMARY KEY (`media_id`),CONSTRAINT `fk_articles_media` FOREIGN KEY (`article_id`) REFERENCES `articles`(`id`));
CREATE INDEX IF NOT EXISTS `idx_media_article_id` ON `media`(`article_id`);
CREATE INDEX IF NOT EXISTS `idx_media_stash_scene_id` ON `media`(`stash_scene_id`);
CREATE INDEX IF NOT EXISTS `idx_media_stash_image_id` ON `media`(`stash_image_id`);
CREATE INDEX IF NOT EXISTS idx_media_article ON media(article_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_media_stash_scene ON media(stash_scene_id) WHERE stash_scene_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_media_status_type ON media(download_status, type);
CREATE TABLE IF NOT EXISTS "accounts"  (`numeric_id` text,`username` text NOT NULL,`display_name` text NOT NULL,`avatar_url` text NOT NULL,`updated_at` datetime NOT NULL,`description` text,`avatar_base64` text,`group_name` text DEFAULT "",`alias_of` text DEFAULT "",`is_whitelist` numeric DEFAULT true, `post_count` integer, `is_trash` boolean NOT NULL DEFAULT false, `trashed_by` text, `trash_reason` text, `trashed_at` datetime,PRIMARY KEY (`numeric_id`));
CREATE INDEX IF NOT EXISTS `idx_accounts_username` ON `accounts`(`username`);
CREATE TABLE IF NOT EXISTS "account_profile_histories"  (`id` integer PRIMARY KEY AUTOINCREMENT,`account_id` text NOT NULL,`display_name` text NOT NULL,`avatar_original_url` text NOT NULL,`avatar_seq` integer NOT NULL,`avatar_virtual_key` text NOT NULL,`observed_at` datetime NOT NULL,`avatar_base64` text,`description` text DEFAULT "",CONSTRAINT `fk_accounts_profile_history` FOREIGN KEY (`account_id`) REFERENCES `accounts`(`numeric_id`));
CREATE INDEX IF NOT EXISTS `idx_account_profile_histories_account_id` ON `account_profile_histories`(`account_id`);
CREATE INDEX IF NOT EXISTS idx_history_lookup ON account_profile_histories(account_id, avatar_seq DESC);
CREATE INDEX IF NOT EXISTS `idx_articles_is_trash` ON `articles`(`is_trash`);
CREATE INDEX IF NOT EXISTS `idx_articles_trashed_by` ON `articles`(`trashed_by`);
CREATE INDEX IF NOT EXISTS `idx_accounts_is_trash` ON `accounts`(`is_trash`);
CREATE INDEX IF NOT EXISTS `idx_media_is_trash` ON `media`(`is_trash`);
CREATE TABLE IF NOT EXISTS `download_reserves` (`id` integer PRIMARY KEY AUTOINCREMENT,`g_id` text,`url` text NOT NULL,`file_name` text,`article_id` text,`media_id` text,`mirror_urls` text,`status` text DEFAULT "reserved",`reason` text,`total_length` integer,`created_at` datetime,`updated_at` datetime);
CREATE INDEX IF NOT EXISTS `idx_download_reserves_status` ON `download_reserves`(`status`);
CREATE INDEX IF NOT EXISTS `idx_download_reserves_media_id` ON `download_reserves`(`media_id`);
CREATE INDEX IF NOT EXISTS `idx_download_reserves_article_id` ON `download_reserves`(`article_id`);
CREATE INDEX IF NOT EXISTS `idx_download_reserves_g_id` ON `download_reserves`(`g_id`);
CREATE TABLE IF NOT EXISTS `thunder_tasks` (`id` text,`media_id` text NOT NULL,`article_id` text,`resolution_type` text NOT NULL,`url` text NOT NULL,`file_name` text NOT NULL,`status` text DEFAULT "PENDING",`dispatched_at` datetime,`completed_at` datetime,`reaped_at` datetime,`created_at` datetime,`updated_at` datetime, `summary_size` text, `error_reason` text, `last_attempt_at` datetime,PRIMARY KEY (`id`));
CREATE INDEX IF NOT EXISTS `idx_thunder_tasks_status` ON `thunder_tasks`(`status`);
CREATE INDEX IF NOT EXISTS `idx_thunder_tasks_file_name` ON `thunder_tasks`(`file_name`);
CREATE INDEX IF NOT EXISTS `idx_thunder_tasks_article_id` ON `thunder_tasks`(`article_id`);
CREATE INDEX IF NOT EXISTS `idx_thunder_tasks_media_id` ON `thunder_tasks`(`media_id`);
CREATE TABLE IF NOT EXISTS "download_tasks"  (media_id TEXT PRIMARY KEY,article_id TEXT,url TEXT NOT NULL,file_name TEXT NOT NULL,`stage` text DEFAULT "REQUESTS",`status` text DEFAULT "PENDING",failed_reason TEXT,requests_at DATETIME,motrix_at DATETIME,thunder_at DATETIME,stash_at DATETIME,completed_at DATETIME,created_at DATETIME,updated_at DATETIME);
CREATE INDEX IF NOT EXISTS `idx_download_tasks_article_id` ON `download_tasks`(`article_id`);
CREATE INDEX IF NOT EXISTS `idx_download_tasks_stage` ON `download_tasks`(`stage`);
CREATE INDEX IF NOT EXISTS `idx_download_tasks_status` ON `download_tasks`(`status`);
CREATE INDEX IF NOT EXISTS idx_media_account ON media(account_id);
CREATE INDEX IF NOT EXISTS `idx_media_account_id` ON `media`(`account_id`);
CREATE TABLE IF NOT EXISTS "media_excluded"  (media_id TEXT PRIMARY KEY,article_id TEXT NOT NULL,account_id TEXT,type TEXT NOT NULL,download_url TEXT NOT NULL,width INTEGER,height INTEGER,download_status TEXT,failed_reason TEXT,tweet_urls TEXT,thumbnail_url TEXT,`quarantined_at` datetime,quarantine_reason TEXT);
CREATE TABLE IF NOT EXISTS `media_variants` (`variant_hash` text,`media_id` text NOT NULL,`article_id` text NOT NULL,`download_url` text NOT NULL,`bit_rate` integer,PRIMARY KEY (`variant_hash`),CONSTRAINT `fk_media_variants` FOREIGN KEY (`media_id`) REFERENCES `media`(`media_id`));
CREATE INDEX IF NOT EXISTS `idx_media_variants_article_id` ON `media_variants`(`article_id`);
CREATE INDEX IF NOT EXISTS `idx_media_variants_media_id` ON `media_variants`(`media_id`);
CREATE TABLE IF NOT EXISTS `account_relations` (`id` text PRIMARY KEY, `source_account_id` text NOT NULL, `target_account_id` text NOT NULL, `target_handle` text, `relation_type` text NOT NULL, `direction` text NOT NULL, `weight` real NOT NULL DEFAULT 1.0, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, CONSTRAINT `fk_account_relations_source` FOREIGN KEY (`source_account_id`) REFERENCES `accounts`(`numeric_id`));
CREATE INDEX IF NOT EXISTS `idx_account_relations_source` ON `account_relations`(`source_account_id`);
CREATE INDEX IF NOT EXISTS `idx_account_relations_target` ON `account_relations`(`target_account_id`);
CREATE TABLE IF NOT EXISTS `article_relation_evidences` (`id` text PRIMARY KEY, `relation_id` text NOT NULL, `source_article_id` text NOT NULL, `target_article_id` text, `evidence_type` text NOT NULL, `context_snippet` text, `media_id` text, `is_salvaged` boolean NOT NULL DEFAULT false, `observed_at` datetime NOT NULL, CONSTRAINT `fk_article_relation_evidences_rel` FOREIGN KEY (`relation_id`) REFERENCES `account_relations`(`id`));
CREATE INDEX IF NOT EXISTS `idx_evidences_relation_id` ON `article_relation_evidences`(`relation_id`);
CREATE INDEX IF NOT EXISTS `idx_evidences_source_article` ON `article_relation_evidences`(`source_article_id`);

-- +goose Down
-- Not generating down migration for baseline
